### ISSUE TITLE
Display models metadata

### ISSUE THREAD

**Issue by Tomansion** [debiai/DebiAI#194]
**Is your feature request related to a problem? Please describe.**
I want to display more data about a model, the data are specific to my project.

**Describe the solution you'd like**
A way to add a json / object / dict / anything to a model on his creation, the content of the metadata is displayed on the front page in the following way : 

![image](https://github.com/debiai/DebiAI/assets/59999324/768df9ae-2166-4f83-85aa-31cf859e0709)

**TODO**

- [x] Modify DebiAI Python module to be able to insert a metadata dict on model creation
- [x] Modify DebiAI Backend to accept store models metadata on the Python-Data-provider API and in the Web-Data-provider API
- [x] Modify DebiAI Backend to provide model metadata when requested the model list
- [x] Modify the DebiAI Frontend to display the models metadata
- [ ] Modify the DebiAI NodeJs template to add some metadata and add the documentation
- [ ] Modify the DebiAI documentation on how to add metadata with the Python module and how to read it in the frontend
