### ISSUE TITLE
Display selections metadata

### ISSUE THREAD

**Issue by FadyCoding** [debiai/DebiAI#203]
**Is your feature request related to a problem? Please describe.**
I want to display more data about a selection, the data is specific to my project.

**Describe the solution you'd like**
A way to add a json / object / dict / anything to a selection on her creation, the content of the metadata is displayed on the front page 

**TODO**

- [ ] Modify DebiAI Backend to accept store selections metadata on the Web-Data-provider API
- [ ] Modify DebiAI Backend to provide selection metadata when requested the selections
- [ ] Modify the DebiAI Frontend to display the selections metadata
- [ ] Modify the DebiAI NodeJs template to add some metadata and add the documentation
- [ ] Modify the DebiAI documentation on how to add metadata with the Python module and how to read it in the frontend
