### ISSUE TITLE
DebiAI easy start module to launch debiAI standlalone

### ISSUE THREAD

**Issue by FadyCoding** [debiai/DebiAI#205]
**Describe the solution you'd like**
Implement a python module that englobs debiAI backend and web DP to have a standalone version of the application.

**Describe alternatives you've considered**

**TODO**

- [x] Modify DebiAI backend as a module
- [x] Launch DebiAI from the new backend module
- [x] Make sure that the tests are through (pipeline, docker, python module)
- [x] Modify the display for ther user in the terminal
- [x] Document the new feature
